let manuals=[],active='All',pendingAttach=null;
const defaultCategories=['Networking','Power','Security','Printers','Other'];let categories=JSON.parse(localStorage.getItem('manualVaultCategories')||'null');if(!Array.isArray(categories)||!categories.length)categories=[...defaultCategories];
const $=s=>document.querySelector(s);
function saveCategories(){localStorage.setItem('manualVaultCategories',JSON.stringify(categories))}
function renderCategories(){const filters=$('#filters');if(filters)filters.innerHTML=[...['All'],...categories.filter(c=>c!=='All')].map(c=>`<button class="chip ${active===c?'active':''}" data-filter="${escapeHtml(c)}">${escapeHtml(c==='All'?'All manuals':c)}</button>`).join('');document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{active=b.dataset.filter;renderCategories();render()});const select=$('#category');if(select)select.innerHTML=categories.map(c=>`<option>${escapeHtml(c)}</option>`).join('');const list=$('#categoryList');if(list)list.innerHTML=categories.map(c=>`<span class="tag">${escapeHtml(c)}</span>`).join('')}
function addCategory(){const input=$('#newCategory');const value=input.value.trim().replace(/\s+/g,' ');if(!value)return;if(categories.some(c=>c.toLowerCase()===value.toLowerCase())){toast('That category already exists');return}categories.push(value);saveCategories();input.value='';renderCategories();toast(`Added category: ${value}`)}
function applyTheme(dark){document.body.classList.toggle('dark',dark);const toggle=$('#themeToggle');if(toggle)toggle.checked=dark;localStorage.setItem('manualVaultTheme',dark?'dark':'light')}
applyTheme(localStorage.getItem('manualVaultTheme')==='dark');
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3000)}
async function api(path,opts={}){const r=await fetch(path,opts);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data}
async function loadManuals(){try{manuals=await api('/api/manuals');render()}catch(e){toast('Server connection failed: '+e.message)}}
function render(){const q=$('#search').value.toLowerCase();const rows=manuals.filter(m=>(active==='All'||m.cat===active)&&(!q||JSON.stringify(m).toLowerCase().includes(q)));$('#count').textContent=manuals.length;$('#makerCount').textContent=new Set(manuals.map(m=>m.maker)).size;$('#pdfCount').textContent=manuals.filter(m=>m.pdf).length;$('#grid').innerHTML=rows.length?rows.map(m=>`<article class="card"><div class="cover"><h3>${escapeHtml(m.title)}</h3></div><b>${escapeHtml(m.maker)}</b><div class="meta">${escapeHtml(m.desc||'')} · ${escapeHtml(m.year||'')}${m.pdf?' · PDF attached':''}</div><div class="tags">${(m.tags||[]).map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join('')}</div><div class="card-actions"><button onclick="openManual('${m.id}')">${m.pdf?'Open PDF':'View record'}</button><button onclick="editManual('${m.id}')">Edit</button><button onclick="attachPdf('${m.id}')">${m.pdf?'Replace PDF':'Attach PDF'}</button><button class="danger" onclick="deleteManual('${m.id}')">Delete</button></div></article>`).join(''):`<div class="empty"><b>No manuals found</b><br/>Try a model number, manufacturer, symptom, or category.</div>`}
async function extractText(file){if(!window.pdfjsLib)return '';try{const doc=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let out='';for(let i=1;i<=doc.numPages;i++){const page=await doc.getPage(i),content=await page.getTextContent();out+=`\n--- Page ${i} ---\n`+content.items.map(x=>x.str).join(' ');if(out.length>120000)break}return out}catch(e){return ''}}
async function uploadPdf(id,file){const isPdf=file&&((file.type||'').toLowerCase()==='application/pdf'||file.name.toLowerCase().endsWith('.pdf'));if(!isPdf)throw new Error('Choose a file ending in .pdf');toast('Reading and uploading PDF…');const text=await extractText(file);const form=new FormData();form.append('pdf',file,file.name);form.append('searchableText',text);await api(`/api/manuals/${id}/pdf`,{method:'POST',body:form});await loadManuals();toast(`Uploaded and indexed ${file.name}`)}
async function openManual(id){const m=manuals.find(x=>x.id===id);$('#modalTitle').textContent=m.title;$('#modal').classList.add('show');const body=$('#viewerBody');if(!m.pdf){body.innerHTML=`<div class="answer"><h3>No PDF attached yet</h3><p>Attach the official PDF from the library card to open and search it here.</p><button class="primary" onclick="attachPdf('${id}')">Attach PDF</button></div>`;return}body.innerHTML=`<div class="viewer"><iframe title="PDF viewer" src="${m.pdfUrl}#toolbar=1&navpanes=0"></iframe><div><input class="reader-search" id="readerSearch" placeholder="Search inside this PDF…"><div class="reader" id="reader">${escapeHtml(m.searchableText||'No text layer found. Use the PDF viewer on the left to read this scanned document.')}</div></div></div>`;$('#readerSearch').oninput=e=>{const q=e.target.value.trim();const text=m.searchableText||'No text layer found. Use the PDF viewer on the left to read this scanned document.';$('#reader').innerHTML=escapeHtml(text).replace(q?new RegExp(escapeRegExp(q),'gi'):/^$a/,x=>`<mark>${x}</mark>`)}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function escapeRegExp(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function attachPdf(id){pendingAttach=id;$('#pdfPicker').click()}
async function deleteManual(id){const m=manuals.find(x=>x.id===id);if(!confirm(`Delete “${m.title}” and its saved PDF?`))return;try{await api(`/api/manuals/${id}`,{method:'DELETE'});await loadManuals();$('#modal').classList.remove('show');toast('Manual deleted')}catch(e){toast(e.message)}}
function editManual(id){const m=manuals.find(x=>x.id===id);if(!m)return;$('#modalTitle').textContent='Edit manual';$('#modal').classList.add('show');$('#viewerBody').innerHTML=`<div class="form edit-form"><label>Title / model</label><input id="editTitle" value="${escapeHtml(m.title)}"><label>Manufacturer</label><input id="editMaker" value="${escapeHtml(m.maker)}"><label>Category</label><select id="editCat">${categories.map(c=>`<option ${c===m.cat?'selected':''}>${escapeHtml(c)}</option>`).join('')}</select><label>Year</label><input id="editYear" value="${escapeHtml(m.year||'')}"><label>Tags <small>(comma separated)</small></label><input id="editTags" value="${escapeHtml((m.tags||[]).join(', '))}"><label>Description / notes</label><textarea id="editDesc">${escapeHtml(m.desc||'')}</textarea><button class="primary" id="saveEdit">Save changes</button></div>`;$('#saveEdit').onclick=async()=>{const payload={title:$('#editTitle').value.trim(),maker:$('#editMaker').value.trim(),cat:$('#editCat').value,year:$('#editYear').value.trim(),tags:$('#editTags').value.split(',').map(x=>x.trim()).filter(Boolean),desc:$('#editDesc').value.trim()};if(!payload.title||!payload.maker){toast('Title and manufacturer are required');return}try{await api(`/api/manuals/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});await loadManuals();$('#modal').classList.remove('show');toast('Manual details updated')}catch(e){toast(e.message)}}}
function switchView(v){const views={library:'libraryView',trouble:'troubleView',intake:'intakeView',settings:'settingsView'};Object.entries(views).forEach(([name,id])=>{const el=document.getElementById(id);if(el)el.style.display=name===v?'block':'none'});document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v||(b.dataset.view==='troubleshoot'&&v==='trouble')))}window.switchView=switchView;function view(v){switchView(v)}
document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view==='troubleshoot'?'trouble':b.dataset.view)));
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{active=b.dataset.filter;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));render()});$('#search').oninput=render;$('#searchBtn').onclick=render;$('#addBtn').onclick=()=>switchView('intake');$('#scanBtn').onclick=()=>{switchView('intake');$('#photo').click()};$('#close').onclick=()=>$('#modal').classList.remove('show');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('show')};
$('#themeToggle').onchange=e=>applyTheme(e.target.checked);
$('#addCategory').onclick=addCategory;renderCategories();
$('#pdfPicker').onchange=async e=>{const file=e.target.files[0];if(file&&pendingAttach!==null)try{await uploadPdf(pendingAttach,file)}catch(err){toast(err.message)}e.target.value='';pendingAttach=null};
$('#saveManual').onclick=async()=>{const form=new FormData();form.append('manufacturer',$('#manufacturer').value.trim()||'Unknown manufacturer');form.append('model',$('#model').value.trim()||'Untitled equipment');form.append('category',$('#category').value);form.append('notes',$('#notes').value.trim());const photo=$('#photo').files[0],pdf=$('#pdfFile').files[0];if(photo)form.append('cover',photo,photo.name);if(pdf){form.append('pdf',pdf,pdf.name);form.append('searchableText',await extractText(pdf))}try{await api('/api/manuals',{method:'POST',body:form});$('#manufacturer').value='';$('#model').value='';$('#notes').value='';$('#pdfFile').value='';$('#photo').value='';await loadManuals();toast('Manual saved to the server');view('library')}catch(e){toast(e.message)}};
$('#solve').onclick=()=>{const issue=$('#issue').value.trim();const box=$('#suggestions');if(!issue){box.innerHTML='<div class="answer">Describe the device and symptom first.</div>';return}const lower=issue.toLowerCase();let m=lower.includes('printer')||lower.includes('paper')?manuals.find(x=>x.maker==='Brother')||manuals[0]:lower.includes('battery')||lower.includes('ups')?manuals.find(x=>x.maker.includes('APC'))||manuals[0]:lower.includes('camera')||lower.includes('nvr')?manuals.find(x=>x.maker==='Hikvision')||manuals[0]:manuals[0];box.innerHTML=`<div class="answer"><h3>Likely starting point</h3><b>${m.title}</b><p>Check the relevant status indicators, power, cabling, and the diagnostic section in the source manual.</p><ol><li>Record the current symptoms and indicator lights.</li><li>Check power, cabling, and the relevant configuration.</li><li>Use the manual's error-code or diagnostic table.</li></ol><div class="source">Source: ${m.title} · <button class="chip" onclick="openManual('${m.id}')">Open manual</button></div></div>`};
$('#suggestions').innerHTML='<div class="answer"><b>Search by symptom</b><p>Try “battery alarm”, “paper jam”, “PoE”, “RAID”, or “POST code”.</p></div><div class="answer"><b>Search by model</b><p>Exact model numbers give the most reliable result.</p></div>';loadManuals();
