let manuals=[],active='All',pendingAttach=null;
const defaultCategories=['Networking','Power','Security','Printers','Other'];let categories=JSON.parse(localStorage.getItem('manualVaultCategories')||'null');if(!Array.isArray(categories)||!categories.length)categories=[...defaultCategories];
const favoriteKey='manualVaultFavorites';function favorites(){try{return JSON.parse(localStorage.getItem(favoriteKey)||'[]')}catch{return []}}function toggleFavorite(event,id){event.stopPropagation();const set=new Set(favorites());set.has(id)?set.delete(id):set.add(id);localStorage.setItem(favoriteKey,JSON.stringify([...set]));render()}function rememberRecent(id){const recent=JSON.parse(localStorage.getItem('manualVaultRecent')||'[]').filter(x=>x!==id);recent.unshift(id);localStorage.setItem('manualVaultRecent',JSON.stringify(recent.slice(0,8)))}
const $=s=>document.querySelector(s);
function saveCategories(){localStorage.setItem('manualVaultCategories',JSON.stringify(categories))}
function renderCategories(){const filters=$('#filters');if(filters)filters.innerHTML=[...['All','Favorites'],...categories.filter(c=>c!=='All')].map(c=>`<button class="chip ${active===c?'active':''}" data-filter="${escapeHtml(c)}">${escapeHtml(c==='All'?'All manuals':c)}</button>`).join('');document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{active=b.dataset.filter;renderCategories();render()});const select=$('#category');if(select)select.innerHTML=categories.map(c=>`<option>${escapeHtml(c)}</option>`).join('');const list=$('#categoryList');if(list)list.innerHTML=categories.map(c=>`<span class="tag">${escapeHtml(c)}</span>`).join('')}
function addCategory(){const input=$('#newCategory');const value=input.value.trim().replace(/\s+/g,' ');if(!value)return;if(categories.some(c=>c.toLowerCase()===value.toLowerCase())){toast('That category already exists');return}categories.push(value);saveCategories();input.value='';renderCategories();toast(`Added category: ${value}`)}
function applyTheme(dark){document.body.classList.toggle('dark',dark);const toggle=$('#themeToggle');if(toggle)toggle.checked=dark;localStorage.setItem('manualVaultTheme',dark?'dark':'light')}
applyTheme(localStorage.getItem('manualVaultTheme')==='dark');
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(()=>{}));
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3000)}
async function api(path,opts={}){const r=await fetch(path,opts);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data}
async function loadManuals(){try{manuals=await api('/api/manuals');render()}catch(e){toast('Server connection failed: '+e.message)}}
function render(){const q=$('#search').value.toLowerCase();const rows=manuals.filter(m=>(active==='All'||(active==='Favorites'&&favorites().includes(m.id))||m.cat===active)&&(!q||JSON.stringify(m).toLowerCase().includes(q)));$('#count').textContent=manuals.length;$('#makerCount').textContent=new Set(manuals.map(m=>m.maker)).size;$('#pdfCount').textContent=manuals.filter(m=>m.pdf).length;$('#grid').innerHTML=rows.length?rows.map(m=>`<article class="card"><div class="cover">${m.coverUrl?`<img src="${m.coverUrl}" alt="Cover of ${escapeHtml(m.title)}" loading="lazy">`:`<div class="cover-fallback"><span>Manual</span><strong>${escapeHtml(m.title)}</strong></div>`}<button class="favorite ${favorites().includes(m.id)?'is-favorite':''}" aria-label="${favorites().includes(m.id)?'Remove from favorites':'Add to favorites'}" onclick="toggleFavorite(event,'${m.id}')">★</button></div><b>${escapeHtml(m.maker)}</b>${m.location?`<div class="meta">${escapeHtml(m.location)}${m.assetTag?' · '+escapeHtml(m.assetTag):''}</div>`:''}<div class="meta">${escapeHtml(m.desc||'')} · ${escapeHtml(m.year||'')}${m.pdf?' · PDF attached':''}</div><div class="tags">${(m.tags||[]).map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join('')}</div><div class="card-actions"><button onclick="openManual('${m.id}')">${m.pdf?'Open PDF':'View record'}</button><button onclick="editManual('${m.id}')">Edit</button><button onclick="attachPdf('${m.id}')">${m.pdf?'Replace PDF':'Attach PDF'}</button><button class="danger" onclick="deleteManual('${m.id}')">Delete</button></div></article>`).join(''):`<div class="empty"><b>No manuals found</b><br/>Try a model number, manufacturer, symptom, or category.</div>`}
async function extractText(file){if(!window.pdfjsLib)return '';try{const doc=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let out='';for(let i=1;i<=doc.numPages;i++){const page=await doc.getPage(i),content=await page.getTextContent();out+=`\n--- Page ${i} ---\n`+content.items.map(x=>x.str).join(' ');if(out.length>120000)break}return out}catch(e){return ''}}
async function uploadPdf(id,file){const isPdf=file&&((file.type||'').toLowerCase()==='application/pdf'||file.name.toLowerCase().endsWith('.pdf'));if(!isPdf)throw new Error('Choose a file ending in .pdf');toast('Reading and uploading PDF…');const text=await extractText(file);const form=new FormData();form.append('pdf',file,file.name);form.append('searchableText',text);await api(`/api/manuals/${id}/pdf`,{method:'POST',body:form});await loadManuals();toast(`Uploaded and indexed ${file.name}`)}
async function openManual(id){const m=manuals.find(x=>x.id===id);rememberRecent(id);$('#modalTitle').textContent=m.title;$('#modal').classList.add('show');const body=$('#viewerBody');if(!m.pdf){body.innerHTML=`<div class="answer"><h3>No PDF attached yet</h3><p>Attach the official PDF from the library card to open and search it here.</p><button class="primary" onclick="attachPdf('${id}')">Attach PDF</button></div>`;return}body.innerHTML=`<div class="viewer"><iframe title="PDF viewer" src="${m.pdfUrl}#toolbar=1&navpanes=0"></iframe><div><input class="reader-search" id="readerSearch" placeholder="Search inside this PDF…"><div class="reader" id="reader">${escapeHtml(m.searchableText||'No text layer found. Use the PDF viewer on the left to read this scanned document.')}</div></div></div>`;$('#readerSearch').oninput=e=>{const q=e.target.value.trim();const text=m.searchableText||'No text layer found. Use the PDF viewer on the left to read this scanned document.';$('#reader').innerHTML=escapeHtml(text).replace(q?new RegExp(escapeRegExp(q),'gi'):/^$a/,x=>`<mark>${x}</mark>`)}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function escapeRegExp(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function attachPdf(id){pendingAttach=id;$('#pdfPicker').click()}
async function deleteManual(id){const m=manuals.find(x=>x.id===id);if(!confirm(`Delete “${m.title}” and its saved PDF?`))return;try{await api(`/api/manuals/${id}`,{method:'DELETE'});await loadManuals();$('#modal').classList.remove('show');toast('Manual deleted')}catch(e){toast(e.message)}}
function editManual(id){const m=manuals.find(x=>x.id===id);if(!m)return;$('#modalTitle').textContent='Edit manual';$('#modal').classList.add('show');$('#viewerBody').innerHTML=`<div class="form edit-form"><label>Title / model</label><input id="editTitle" value="${escapeHtml(m.title)}"><label>Manufacturer</label><input id="editMaker" value="${escapeHtml(m.maker)}"><label>Asset tag</label><input id="editAssetTag" value="${escapeHtml(m.assetTag||'')}"><label>Serial number</label><input id="editSerial" value="${escapeHtml(m.serialNumber||'')}"><label>Location / site</label><input id="editLocation" value="${escapeHtml(m.location||'')}"><label>Installed firmware</label><input id="editFirmware" value="${escapeHtml(m.firmware||'')}"><label>Category</label><select id="editCat">${categories.map(c=>`<option ${c===m.cat?'selected':''}>${escapeHtml(c)}</option>`).join('')}</select><label>Year</label><input id="editYear" value="${escapeHtml(m.year||'')}"><label>Tags <small>(comma separated)</small></label><input id="editTags" value="${escapeHtml((m.tags||[]).join(', '))}"><label>Description / notes</label><textarea id="editDesc">${escapeHtml(m.desc||'')}</textarea><button class="primary" id="saveEdit">Save changes</button></div>`;$('#saveEdit').onclick=async()=>{const payload={title:$('#editTitle').value.trim(),maker:$('#editMaker').value.trim(),assetTag:$('#editAssetTag').value.trim(),serialNumber:$('#editSerial').value.trim(),location:$('#editLocation').value.trim(),firmware:$('#editFirmware').value.trim(),cat:$('#editCat').value,year:$('#editYear').value.trim(),tags:$('#editTags').value.split(',').map(x=>x.trim()).filter(Boolean),desc:$('#editDesc').value.trim()};if(!payload.title||!payload.maker){toast('Title and manufacturer are required');return}try{await api(`/api/manuals/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});await loadManuals();$('#modal').classList.remove('show');toast('Manual details updated')}catch(e){toast(e.message)}}}
function switchView(v){const views={library:'libraryView',trouble:'troubleView',intake:'intakeView',settings:'settingsView'};Object.entries(views).forEach(([name,id])=>{const el=document.getElementById(id);if(el)el.style.display=name===v?'block':'none'});document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v||(b.dataset.view==='troubleshoot'&&v==='trouble')))}window.switchView=switchView;function view(v){switchView(v)}
document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view==='troubleshoot'?'trouble':b.dataset.view)));
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{active=b.dataset.filter;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));render()});$('#search').oninput=render;$('#searchBtn').onclick=render;$('#addBtn').onclick=()=>switchView('intake');$('#scanBtn').onclick=()=>{switchView('intake');$('#photo').click()};$('#close').onclick=()=>$('#modal').classList.remove('show');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('show')};
$('#themeToggle').onchange=e=>applyTheme(e.target.checked);
$('#addCategory').onclick=addCategory;renderCategories();
$('#downloadBackup').onclick=async()=>{try{const data=await api('/api/backup');const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`manual-vault-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup downloaded')}catch(e){toast(e.message)}};
$('#installOffline').onclick=async()=>{if(navigator.serviceWorker){await navigator.serviceWorker.ready;toast('Offline shell prepared; opened manuals will be cached when possible')}else toast('Offline mode is unavailable in this browser')};
$('#pdfPicker').onchange=async e=>{const file=e.target.files[0];if(file&&pendingAttach!==null)try{await uploadPdf(pendingAttach,file)}catch(err){toast(err.message)}e.target.value='';pendingAttach=null};
$('#photo').onchange=async e=>{const file=e.target.files[0];if(!file||!window.Tesseract)return;toast('Reading cover text…');try{const result=await Tesseract.recognize(file,'eng');const text=result.data.text.replace(/\s+/g,' ').trim();const makers=['Ubiquiti','APC','Schneider','Brother','Synology','Hikvision','Dell','Lenovo','HP','Cisco','Aruba','Epson','Canon','Sony','Logitech','NEXIGO','Acer','ACER'];const maker=makers.find(x=>text.toLowerCase().includes(x.toLowerCase()));if(maker&&!$('#manufacturer').value)$('#manufacturer').value=maker;const modelMatch=text.match(/\b[A-Z0-9][A-Z0-9+._/-]{3,}\b/g)||[];const model=modelMatch.find(x=>!makers.some(m=>m.toLowerCase()===x.toLowerCase())&&/[0-9]/.test(x));if(model&&!$('#model').value)$('#model').value=model;$('#notes').value=$('#notes').value||`OCR text: ${text.slice(0,500)}`;toast('Cover scanned — review the detected fields')}catch(e){toast('Cover OCR could not read this image; enter the details manually')}};
$('#saveManual').onclick=async()=>{const form=new FormData();form.append('manufacturer',$('#manufacturer').value.trim()||'Unknown manufacturer');form.append('model',$('#model').value.trim()||'Untitled equipment');form.append('category',$('#category').value);form.append('notes',$('#notes').value.trim());const photo=$('#photo').files[0],pdf=$('#pdfFile').files[0];if(photo)form.append('cover',photo,photo.name);if(pdf){form.append('pdf',pdf,pdf.name);form.append('searchableText',await extractText(pdf))}try{await api('/api/manuals',{method:'POST',body:form});$('#manufacturer').value='';$('#model').value='';$('#notes').value='';$('#pdfFile').value='';$('#photo').value='';await loadManuals();toast('Manual saved to the server');view('library')}catch(e){toast(e.message)}};
$('#solve').onclick=()=>{const issue=$('#issue').value.trim();const box=$('#suggestions');if(!issue){box.innerHTML='<div class="answer">Describe the device and symptom first.</div>';return}const lower=issue.toLowerCase();let m=lower.includes('printer')||lower.includes('paper')?manuals.find(x=>x.maker==='Brother')||manuals[0]:lower.includes('battery')||lower.includes('ups')?manuals.find(x=>x.maker.includes('APC'))||manuals[0]:lower.includes('camera')||lower.includes('nvr')?manuals.find(x=>x.maker==='Hikvision')||manuals[0]:manuals[0];box.innerHTML=`<div class="answer"><h3>Likely starting point</h3><b>${m.title}</b><p>Check the relevant status indicators, power, cabling, and the diagnostic section in the source manual.</p><ol><li>Record the current symptoms and indicator lights.</li><li>Check power, cabling, and the relevant configuration.</li><li>Use the manual's error-code or diagnostic table.</li></ol><div class="source">Source: ${m.title} · <button class="chip" onclick="openManual('${m.id}')">Open manual</button></div></div>`};
function groundedMatch(issue){const terms=issue.toLowerCase().split(/[^a-z0-9-]+/).filter(x=>x.length>2);return manuals.map(m=>{const hay=JSON.stringify(m).toLowerCase();const score=terms.reduce((n,t)=>n+(hay.includes(t)?1:0),0);const text=m.searchableText||'';let match=-1;for(const t of terms){const i=text.toLowerCase().indexOf(t);if(i>=0){match=i;break}}return {m,score,match}}).sort((a,b)=>b.score-a.score)[0]}
$('#solve').onclick=()=>{const issue=$('#issue').value.trim();const box=$('#suggestions');if(!issue){box.innerHTML='<div class="answer">Describe the device and symptom first.</div>';return}const hit=groundedMatch(issue);if(!hit||hit.score===0){box.innerHTML='<div class="answer"><h3>No grounded match yet</h3><p>No indexed manual contains enough of those terms. Try the exact model, an error code, or attach/search the correct PDF first.</p></div>';return}const page=hit.match>=0?((hit.m.searchableText.slice(0,hit.match).match(/--- Page (\d+) ---/g)||[]).pop()||'Indexed text'):'Manual metadata';const excerpt=hit.match>=0?hit.m.searchableText.slice(Math.max(0,hit.match-120),hit.match+320).replace(/--- Page \d+ ---/g,'').trim():'Open the manual and search its indexed text for the exact symptom or code.';box.innerHTML=`<div class="answer"><h3>Grounded starting point</h3><b>${escapeHtml(hit.m.title)}</b><p><b>Source:</b> ${escapeHtml(page)}</p><p>${escapeHtml(excerpt)}</p><button class="primary" onclick="openManual('${hit.m.id}')">Open source manual</button></div>`};
loadManuals();